import {Knex} from "knex";

export async function seed(knex: Knex): Promise<void> {
    // Deletes ALL existing entries
    await knex("actors").del();

    const actors = [
        {name: "Tim Robbins"},
        {name: "Morgan Freeman"},
        {name: "Bob Gunton"},
        {name: "Marlon Brando"},
        {name: "Al Pacino"},
        {name: "James Caan"},
        {name: "Robert De Niro"},
        {name: "Robert Duvall"},
        {name: "Diane Keaton"},
        {name: "Andy Garcia"},
        {name: "Christian Bale"},
        {name: "Michael Caine"},
        {name: "Ken Watanabe"},
        {name: "Heath Ledger"},
        {name: "Aaron Eckhart"},
        {name: "Tom Hardy"},
        {name: "Anne Hathaway"},
        {name: "Elijah Wood"},
        {name: "Ian McKellen"},
        {name: "Viggo Mortensen"},
        {name: "Orlando Bloom"},
        {name: "Clint Eastwood"},
        {name: "Eli Wallach"},
        {name: "Lee Van Cleef"},
        {name: "Tom Hanks"},
        {name: "Robin Wright"},
        {name: "Gary Sinise"},
        {name: "Brad Pitt"},
        {name: "Edward Norton"},
        {name: "Meat Loaf"},
        {name: "Leonardo DiCaprio"},
        {name: "Joseph Gordon-Levitt"},
        {name: "Elliot Page"},
        {name: "Ray Liotta"},
        {name: "Joe Pesci"},
        {name: "Keanu Reeves"},
        {name: "Laurence Fishburne"},
        {name: "Carrie-Anne Moss"},
        {name: "Yahya Abdul-Mateen II"},
        {name: "Jodie Foster"},
        {name: "Anthony Hopkins"},
        {name: "Lawrence A. Bonney"},
        {name: "Matt Damon"},
        {name: "Tom Sizemore"},
        {name: "Michael Clarke Duncan"},
        {name: "David Morse"},
        {name: "Matthew McConaughey"},
        {name: "Jessica Chastain"},
        {name: "Daveigh Chase"},
        {name: "Suzanne Pleshette"},
        {name: "Miyu Irino"},
        {name: "Matthew Broderick"},
        {name: "Jeremy Irons"},
        {name: "James Earl Jones"},
        {name: "Russell Crowe"},
        {name: "Joaquin Phoenix"},
        {name: "Connie Nielsen"},
        {name: "Jack Nicholson"},
        {name: "Hugh Jackman"},
        {name: "Scarlett Johansson"},
        {name: "Tsutomu Tatsumi"},
        {name: "Ayano Shiraishi"},
        {name: "Akemi Yamaguchi"},
        {name: "Tom Cruise"},
        {name: "Jennifer Connelly"},
        {name: "Miles Teller"},
        {name: "Guy Pearce"},
        {name: "Joe Pantoliano"},
        {name: "Ben Burtt"},
        {name: "Elissa Knight"},
        {name: "Jeff Garlin"},
        {name: "Robert Downey Jr."},
        {name: "Chris Hemsworth"},
        {name: "Mark Ruffalo"},
        {name: "Shameik Moore"},
        {name: "Jake Johnson"},
        {name: "Hailee Steinfeld"},
        {name: "Mel Gibson"},
        {name: "Sophie Marceau"},
        {name: "Patrick McGoohan"},
        {name: "Tim Allen"},
        {name: "Don Rickles"},
        {name: "Diane Kruger"},
        {name: "Eli Roth"},
        {name: "Yôji Matsuda"},
        {name: "Yuriko Ishida"},
        {name: "Yûko Tanaka"},
        {name: "Chris Evans"},
        {name: "Robin Williams"},
        {name: "Ben Affleck"},
        {name: "Ryûnosuke Kamiki"},
        {name: "Mone Kamishiraishi"},
        {name: "Ryô Narita"},
        {name: "Ellen Burstyn"},
        {name: "Jared Leto"},
        {name: "Ed Harris"},
        {name: "Christopher Walken"},
        {name: "Harrison Ford"},
        {name: "Rutger Hauer"},
        {name: "Sean Young"},
        {name: "Ryan Gosling"},
        {name: "Ana de Armas"},
        {name: "Hitoshi Takagi"},
        {name: "Noriko Hidaka"},
        {name: "Chika Sakamoto"},
        {name: "Jason Schwartzman"},
        {name: "J.K. Simmons"},
        {name: "Rashida Jones"},
        {name: "Jon Bernthal"},
        {name: "Chieko Baishô"},
        {name: "Takuya Kimura"},
        {name: "Tatsuya Gashûin"}
    ]

    // Inserts seed entries
    await knex("actors").insert(actors)

    // After seeding insert for postgres integer ids needs to be synced
    await knex.raw('select setval(\'actors_id_seq\', max(id)) from actors')
}
