export const MOVIE_DATA = [
    {
        title: "The Shawshank Redemption",
        description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        release_date: "1994-10-14",
        img: "tt0111161.jpg",
        thumb: "thumb_tt0111161.png",
        running_time: "142 min",
        rating: "R",
        box_office: "$28,767,189",
        genre: "Drama",
        actors: "Tim Robbins, Morgan Freeman, Bob Gunton",
        rental_rate: 3,
        rental_duration: "4 days",
        damage_cost: 5
    },
    {
        title: "The Godfather",
        description: "The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son.",
        release_date: "1972-03-24",
        img: "tt0068646.jpg",
        thumb: "thumb_tt0068646.png",
        running_time: "175 min",
        rating: "R",
        box_office: "$136,381,073",
        genre: "Crime, Drama",
        actors: "Marlon Brando, Al Pacino, James Caan",
        rental_rate: 2,
        rental_duration: "6 days",
        damage_cost: 4
    },
    {
        title: "The Godfather Part II",
        description: "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
        release_date: "1974-12-18",
        img: "tt0071562.jpg",
        thumb: "thumb_tt0071562.png",
        running_time: "202 min",
        rating: "R",
        box_office: "$47,834,595",
        genre: "Crime, Drama",
        actors: "Al Pacino, Robert De Niro, Robert Duvall",
        rental_rate: 4,
        rental_duration: "3 days",
        damage_cost: 6
    },
    {
        title: "The Godfather Part III",
        description: "Follows Michael Corleone, now in his 60s, as he seeks to free his family from crime and find a suitable successor to his empire.",
        release_date: "1990-12-25",
        img: "tt0099674.jpg",
        thumb: "thumb_tt0099674.png",
        running_time: "162 min",
        rating: "R",
        box_office: "$66,761,392",
        genre: "Crime, Drama",
        actors: "Al Pacino, Diane Keaton, Andy Garcia",
        rental_rate: 25,
        rental_duration: "4 days",
        damage_cost: 27
    },
    {
        title: "Batman Begins",
        description: "After training with his mentor, Batman begins his fight to free crime-ridden Gotham City from corruption.",
        release_date: "2005-06-15",
        img: "tt0372784.jpg",
        thumb: "thumb_tt0372784.png",
        running_time: "140 min",
        rating: "PG-13",
        box_office: "$206,863,479",
        genre: "Action, Crime, Drama",
        actors: "Christian Bale, Michael Caine, Ken Watanabe",
        rental_rate: 4,
        rental_duration: "6 days",
        damage_cost: 6
    },
    {
        title: "The Dark Knight",
        description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
        release_date: "2008-07-18",
        img: "tt0468569.jpg",
        thumb: "thumb_tt0468569.png",
        running_time: "152 min",
        rating: "PG-13",
        box_office: "$534,987,076",
        genre: "Action, Crime, Drama",
        actors: "Christian Bale, Heath Ledger, Aaron Eckhart",
        rental_rate: 16,
        rental_duration: "7 days",
        damage_cost: 18
    },
    {
        title: "The Dark Knight Rises",
        description: "Eight years after the Joker's reign of anarchy, Batman, with the help of the enigmatic Catwoman, is forced from his exile to save Gotham City from the brutal guerrilla terrorist Bane.",
        release_date: "2012-07-20",
        img: "tt1345836.jpg",
        thumb: "thumb_tt1345836.png",
        running_time: "164 min",
        rating: "PG-13",
        box_office: "$448,149,584",
        genre: "Action, Drama",
        actors: "Christian Bale, Tom Hardy, Anne Hathaway",
        rental_rate: 2,
        rental_duration: "2 days",
        damage_cost: 4
    },
    {
        title: "The Lord of the Rings: The Two Towers",
        description: "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.",
        release_date: "2002-12-18",
        img: "tt0167261.jpg",
        thumb: "thumb_tt0167261.png",
        running_time: "179 min",
        rating: "PG-13",
        box_office: "$342,952,511",
        genre: "Action, Adventure, Drama",
        actors: "Elijah Wood, Ian McKellen, Viggo Mortensen",
        rental_rate: 3,
        rental_duration: "6 days",
        damage_cost: 5
    },
    {
        title: "The Lord of the Rings: The Fellowship of the Ring",
        description: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
        release_date: "2001-12-19",
        img: "tt0120737.jpg",
        thumb: "thumb_tt0120737.png",
        running_time: "178 min",
        rating: "PG-13",
        box_office: "$316,115,420",
        genre: "Action, Adventure, Drama",
        actors: "Elijah Wood, Ian McKellen, Orlando Bloom",
        rental_rate: 20,
        rental_duration: "4 days",
        damage_cost: 22
    },
    {
        title: "The Lord of the Rings: The Return of the King",
        description: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
        release_date: "2003-12-17",
        img: "tt0167260.jpg",
        thumb: "thumb_tt0167260.png",
        running_time: "201 min",
        rating: "PG-13",
        box_office: "$378,251,207",
        genre: "Action, Adventure, Drama",
        actors: "Elijah Wood, Viggo Mortensen, Ian McKellen",
        rental_rate: 15,
        rental_duration: "2 days",
        damage_cost: 17
    },
    {
        title: "The Good, the Bad and the Ugly",
        description: "A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.",
        release_date: "1967-12-29",
        img: "tt0060196.jpg",
        thumb: "thumb_tt0060196.png",
        running_time: "178 min",
        rating: "R",
        box_office: "$25,100,000",
        genre: "Adventure, Western",
        actors: "Clint Eastwood, Eli Wallach, Lee Van Cleef",
        rental_rate: 5,
        rental_duration: "6 days",
        damage_cost: 7
    },
    {
        title: "Forrest Gump",
        description: "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood swe...",
        release_date: "1994-07-06",
        img: "tt0109830.jpg",
        thumb: "thumb_tt0109830.png",
        running_time: "142 min",
        rating: "PG-13",
        box_office: "$330,455,270",
        genre: "Drama, Romance",
        actors: "Tom Hanks, Robin Wright, Gary Sinise",
        rental_rate: 1,
        rental_duration: "6 days",
        damage_cost: 3
    },
    {
        title: "Fight Club",
        description: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
        release_date: "1999-10-15",
        img: "tt0137523.jpg",
        thumb: "thumb_tt0137523.png",
        running_time: "139 min",
        rating: "R",
        box_office: "$37,030,102",
        genre: "Drama",
        actors: "Brad Pitt, Edward Norton, Meat Loaf",
        rental_rate: 2,
        rental_duration: "3 days",
        damage_cost: 4
    },
    {
        title: "Inception",
        description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
        release_date: "2010-07-16",
        img: "tt1375666.jpg",
        thumb: "thumb_tt1375666.png",
        running_time: "148 min",
        rating: "PG-13",
        box_office: "$292,587,330",
        genre: "Action, Adventure, Sci-Fi",
        actors: "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
        rental_rate: 3,
        rental_duration: "4 days",
        damage_cost: 5
    },
    {
        title: "Goodfellas",
        description: "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.",
        release_date: "1990-09-21",
        img: "tt0099685.jpg",
        thumb: "thumb_tt0099685.png",
        running_time: "145 min",
        rating: "R",
        box_office: "$46,909,721",
        genre: "Biography, Crime, Drama",
        actors: "Robert De Niro, Ray Liotta, Joe Pesci",
        rental_rate: 4,
        rental_duration: "4 days",
        damage_cost: 6
    },
    {
        title: "The Matrix",
        description: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
        release_date: "1999-03-31",
        img: "tt0133093.jpg",
        thumb: "thumb_tt0133093.png",
        running_time: "136 min",
        rating: "R",
        box_office: "$172,076,928",
        genre: "Action, Sci-Fi",
        actors: "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
        rental_rate: 3,
        rental_duration: "2 days",
        damage_cost: 5
    },
    {
        title: "The Matrix Reloaded",
        description: "Freedom fighters Neo, Trinity and Morpheus continue to lead the revolt against the Machine Army, unleashing their arsenal of extraordinary skills and weaponry against the systematic forces of repression and exploitation.",
        release_date: "2003-05-15",
        img: "tt0234215.jpg",
        thumb: "thumb_tt0234215.png",
        running_time: "138 min",
        rating: "R",
        box_office: "$281,576,461",
        genre: "Action, Sci-Fi",
        actors: "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
        rental_rate: 16,
        rental_duration: "1 days",
        damage_cost: 18
    },
    {
        title: "The Matrix Revolutions",
        description: "The human city of Zion defends itself against the massive invasion of the machines as Neo fights to end the war at another front while also opposing the rogue Agent Smith.",
        release_date: "2003-11-05",
        img: "tt0242653.jpg",
        thumb: "thumb_tt0242653.png",
        running_time: "129 min",
        rating: "R",
        box_office: "$139,313,948",
        genre: "Action, Sci-Fi",
        actors: "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
        rental_rate: 2,
        rental_duration: "4 days",
        damage_cost: 4
    },
    {
        title: "The Matrix Resurrections",
        description: "Return to a world of two realities: one, everyday life; the other, what lies behind it. To find out if his reality is a construct, to truly know himself, Mr. Anderson will have to choose to follow the white rabbit once more.",
        release_date: "2021-12-22",
        img: "tt10838180.jpg",
        thumb: "thumb_tt10838180.png",
        running_time: "148 min",
        rating: "R",
        box_office: "$37,686,805",
        genre: "Action, Sci-Fi",
        actors: "Keanu Reeves, Carrie-Anne Moss, Yahya Abdul-Mateen II",
        rental_rate: 3,
        rental_duration: "2 days",
        damage_cost: 5
    },
    {
        title: "The Silence of the Lambs",
        description: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
        release_date: "1991-02-14",
        img: "tt0102926.jpg",
        thumb: "thumb_tt0102926.png",
        running_time: "118 min",
        rating: "R",
        box_office: "$130,742,922",
        genre: "Crime, Drama, Thriller",
        actors: "Jodie Foster, Anthony Hopkins, Lawrence A. Bonney",
        rental_rate: 12,
        rental_duration: "1 days",
        damage_cost: 14
    },
    {
        title: "Saving Private Ryan",
        description: "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
        release_date: "1998-07-24",
        img: "tt0120815.jpg",
        thumb: "thumb_tt0120815.png",
        running_time: "169 min",
        rating: "R",
        box_office: "$217,049,603",
        genre: "Drama, War",
        actors: "Tom Hanks, Matt Damon, Tom Sizemore",
        rental_rate: 10,
        rental_duration: "2 days",
        damage_cost: 12
    },
    {
        title: "The Green Mile",
        description: "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
        release_date: "1999-12-10",
        img: "tt0120689.jpg",
        thumb: "thumb_tt0120689.png",
        running_time: "189 min",
        rating: "R",
        box_office: "$136,801,374",
        genre: "Crime, Drama, Fantasy",
        actors: "Tom Hanks, Michael Clarke Duncan, David Morse",
        rental_rate: 10,
        rental_duration: "1 days",
        damage_cost: 12
    },
    {
        title: "Interstellar",
        description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
        release_date: "2014-11-07",
        img: "tt0816692.jpg",
        thumb: "thumb_tt0816692.png",
        running_time: "169 min",
        rating: "PG-13",
        box_office: "$188,020,017",
        genre: "Adventure, Drama, Sci-Fi",
        actors: "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
        rental_rate: 3,
        rental_duration: "2 days",
        damage_cost: 5
    },
    {
        title: "Spirited Away",
        description: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.",
        release_date: "2003-03-28",
        img: "tt0245429.jpg",
        thumb: "thumb_tt0245429.png",
        running_time: "125 min",
        rating: "PG",
        box_office: "$13,750,644",
        genre: "Animation, Adventure, Family",
        actors: "Daveigh Chase, Suzanne Pleshette, Miyu Irino",
        rental_rate: 16,
        rental_duration: "3 days",
        damage_cost: 18
    },
    {
        title: "The Lion King",
        description: "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
        release_date: "1994-06-24",
        img: "tt0110357.jpg",
        thumb: "thumb_tt0110357.png",
        running_time: "88 min",
        rating: "G",
        box_office: "$422,783,777",
        genre: "Animation, Adventure, Drama",
        actors: "Matthew Broderick, Jeremy Irons, James Earl Jones",
        rental_rate: 4,
        rental_duration: "4 days",
        damage_cost: 6
    },
    {
        title: "Gladiator",
        description: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
        release_date: "2000-05-05",
        img: "tt0172495.jpg",
        thumb: "thumb_tt0172495.png",
        running_time: "155 min",
        rating: "R",
        box_office: "$187,705,427",
        genre: "Action, Adventure, Drama",
        actors: "Russell Crowe, Joaquin Phoenix, Connie Nielsen",
        rental_rate: 25,
        rental_duration: "1 days",
        damage_cost: 27
    },
    {
        title: "The Departed",
        description: "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.",
        release_date: "2006-10-06",
        img: "tt0407887.jpg",
        thumb: "thumb_tt0407887.png",
        running_time: "151 min",
        rating: "R",
        box_office: "$132,399,394",
        genre: "Crime, Drama, Thriller",
        actors: "Leonardo DiCaprio, Matt Damon, Jack Nicholson",
        rental_rate: 20,
        rental_duration: "4 days",
        damage_cost: 22
    },
    {
        title: "The Prestige",
        description: "After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.",
        release_date: "2006-10-20",
        img: "tt0482571.jpg",
        thumb: "thumb_tt0482571.png",
        running_time: "130 min",
        rating: "PG-13",
        box_office: "$53,089,891",
        genre: "Drama, Mystery, Sci-Fi",
        actors: "Christian Bale, Hugh Jackman, Scarlett Johansson",
        rental_rate: 15,
        rental_duration: "4 days",
        damage_cost: 17
    },
    {
        title: "Grave of the Fireflies",
        description: "A young boy and his little sister struggle to survive in Japan during World War II.",
        release_date: "1989-07-26",
        img: "tt0095327.jpg",
        thumb: "thumb_tt0095327.png",
        running_time: "89 min",
        rating: "Not Rated",
        box_office: "$516,962",
        genre: "Animation, Drama, War",
        actors: "Tsutomu Tatsumi, Ayano Shiraishi, Akemi Yamaguchi",
        rental_rate: 15,
        rental_duration: "5 days",
        damage_cost: 17
    },
    {
        title: "Top Gun: Maverick",
        description: "After more than thirty years of service as one of the Navy's top aviators, Pete Mitchell is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank that would ground him.",
        release_date: "2022-05-27",
        img: "tt1745960.jpg",
        thumb: "thumb_tt1745960.png",
        running_time: "130 min",
        rating: "PG-13",
        box_office: "$641,903,700",
        genre: "Action, Drama",
        actors: "Tom Cruise, Jennifer Connelly, Miles Teller",
        rental_rate: 20,
        rental_duration: "2 days",
        damage_cost: 22
    },
    {
        title: "Memento",
        description: "A man with short-term memory loss attempts to track down his wife's murderer.",
        release_date: "2001-05-25",
        img: "tt0209144.jpg",
        thumb: "thumb_tt0209144.png",
        running_time: "113 min",
        rating: "R",
        box_office: "$25,544,867",
        genre: "Mystery, Thriller",
        actors: "Guy Pearce, Carrie-Anne Moss, Joe Pantoliano",
        rental_rate: 15,
        rental_duration: "4 days",
        damage_cost: 17
    },
    {
        title: "WALL·E",
        description: "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.",
        release_date: "2008-06-27",
        img: "tt0910970.jpg",
        thumb: "thumb_tt0910970.png",
        running_time: "98 min",
        rating: "G",
        box_office: "$223,808,164",
        genre: "Animation, Adventure, Family",
        actors: "Ben Burtt, Elissa Knight, Jeff Garlin",
        rental_rate: 3,
        rental_duration: "1 days",
        damage_cost: 5
    },
    {
        title: "Avengers: Infinity War",
        description: "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.",
        release_date: "2018-04-27",
        img: "tt4154756.jpg",
        thumb: "thumb_tt4154756.png",
        running_time: "149 min",
        rating: "PG-13",
        box_office: "$678,815,482",
        genre: "Action, Adventure, Sci-Fi",
        actors: "Robert Downey Jr., Chris Hemsworth, Mark Ruffalo",
        rental_rate: 15,
        rental_duration: "1 days",
        damage_cost: 17
    },
    {
        title: "Spider-Man: Into the Spider-Verse",
        description: "Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.",
        release_date: "2018-12-14",
        img: "tt4633694.jpg",
        thumb: "thumb_tt4633694.png",
        running_time: "117 min",
        rating: "PG",
        box_office: "$190,241,310",
        genre: "Animation, Action, Adventure",
        actors: "Shameik Moore, Jake Johnson, Hailee Steinfeld",
        rental_rate: 1,
        rental_duration: "1 days",
        damage_cost: 3
    },
    {
        title: "Braveheart",
        description: "Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England.",
        release_date: "1995-05-24",
        img: "tt0112573.jpg",
        thumb: "thumb_tt0112573.png",
        running_time: "178 min",
        rating: "R",
        box_office: "$75,609,945",
        genre: "Biography, Drama, History",
        actors: "Mel Gibson, Sophie Marceau, Patrick McGoohan",
        rental_rate: 10,
        rental_duration: "3 days",
        damage_cost: 12
    },
    {
        title: "Toy Story",
        description: "A cowboy doll is profoundly threatened and jealous when a new spaceman action figure supplants him as top toy in a boy's bedroom.",
        release_date: "1995-11-22",
        img: "tt0114709.jpg",
        thumb: "thumb_tt0114709.png",
        running_time: "81 min",
        rating: "G",
        box_office: "$223,225,679",
        genre: "Animation, Adventure, Comedy",
        actors: "Tom Hanks, Tim Allen, Don Rickles",
        rental_rate: 2,
        rental_duration: "3 days",
        damage_cost: 4
    },
    {
        title: "Inglourious Basterds",
        description: "In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans for the same.",
        release_date: "2009-08-21",
        img: "tt0361748.jpg",
        thumb: "thumb_tt0361748.png",
        running_time: "153 min",
        rating: "R",
        box_office: "$120,540,719",
        genre: "Adventure, Drama, War",
        actors: "Brad Pitt, Diane Kruger, Eli Roth",
        rental_rate: 6,
        rental_duration: "1 days",
        damage_cost: 8
    },
    {
        title: "Princess Mononoke",
        description: "On a journey to find the cure for a Tatarigami's curse, Ashitaka finds himself in the middle of a war between the forest gods and Tatara, a mining colony. In this quest he also meets San, the Mononoke Hime.",
        release_date: "1997-12-19",
        img: "tt0119698.jpg",
        thumb: "thumb_tt0119698.png",
        running_time: "134 min",
        rating: "PG-13",
        box_office: "$4,845,631",
        genre: "Animation, Adventure, Fantasy",
        actors: "Yôji Matsuda, Yuriko Ishida, Yûko Tanaka",
        rental_rate: 9,
        rental_duration: "2 days",
        damage_cost: 11
    },
    {
        title: "Avengers: Endgame",
        description: "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
        release_date: "2019-04-26",
        img: "tt4154796.jpg",
        thumb: "thumb_tt4154796.png",
        running_time: "181 min",
        rating: "PG-13",
        box_office: "$858,373,000",
        genre: "Action, Adventure, Drama",
        actors: "Robert Downey Jr., Chris Evans, Mark Ruffalo",
        rental_rate: 6,
        rental_duration: "3 days",
        damage_cost: 8
    },
    {
        title: "Good Will Hunting",
        description: "Will Hunting, a janitor at M.I.T., has a gift for mathematics, but needs help from a psychologist to find direction in his life.",
        release_date: "1998-01-09",
        img: "tt0119217.jpg",
        thumb: "thumb_tt0119217.png",
        running_time: "126 min",
        rating: "R",
        box_office: "$138,433,435",
        genre: "Drama, Romance",
        actors: "Robin Williams, Matt Damon, Ben Affleck",
        rental_rate: 10,
        rental_duration: "1 days",
        damage_cost: 12
    },
    {
        title: "Your Name.",
        description: "Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?",
        release_date: "2017-04-07",
        img: "tt5311514.jpg",
        thumb: "thumb_tt5311514.png",
        running_time: "106 min",
        rating: "TV-PG",
        box_office: "$5,017,246",
        genre: "Animation, Drama, Fantasy",
        actors: "Ryûnosuke Kamiki, Mone Kamishiraishi, Ryô Narita",
        rental_rate: 15,
        rental_duration: "4 days",
        damage_cost: 17
    },
    {
        title: "Requiem for a Dream",
        description: "The drug-induced utopias of four Coney Island people are shattered when their addictions run deep.",
        release_date: "2000-12-15",
        img: "tt0180093.jpg",
        thumb: "thumb_tt0180093.png",
        running_time: "102 min",
        rating: "Unrated",
        box_office: "$3,635,482",
        genre: "Drama",
        actors: "Ellen Burstyn, Jared Leto, Jennifer Connelly",
        rental_rate: 8,
        rental_duration: "3 days",
        damage_cost: 10
    },
    {
        title: "A Beautiful Mind",
        description: "After John Nash, a brilliant but asocial mathematician, accepts secret work in cryptography, his life takes a turn for the nightmarish.",
        release_date: "2002-01-04",
        img: "tt0268978.jpg",
        thumb: "thumb_tt0268978.png",
        running_time: "135 min",
        rating: "PG-13",
        box_office: "$170,742,341",
        genre: "Biography, Drama",
        actors: "Russell Crowe, Ed Harris, Jennifer Connelly",
        rental_rate: 4,
        rental_duration: "5 days",
        damage_cost: 6
    },
    {
        title: "Catch Me If You Can",
        description: "Barely 21 yet, Frank is a skilled forger who has passed as a doctor, lawyer and pilot. FBI agent Carl becomes obsessed with tracking down the con man, who only revels in the pursuit.",
        release_date: "2002-12-25",
        img: "tt0264464.jpg",
        thumb: "thumb_tt0264464.png",
        running_time: "141 min",
        rating: "PG-13",
        box_office: "$164,615,351",
        genre: "Biography, Crime, Drama",
        actors: "Leonardo DiCaprio, Tom Hanks, Christopher Walken",
        rental_rate: 15,
        rental_duration: "4 days",
        damage_cost: 17
    },
    {
        title: "Blade Runner",
        description: "A blade runner must pursue and terminate four replicants who stole a ship in space, and have returned to Earth to find their creator.",
        release_date: "1982-06-25",
        img: "tt0083658.jpg",
        thumb: "thumb_tt0083658.png",
        running_time: "117 min",
        rating: "R",
        box_office: "$32,914,489",
        genre: "Action, Drama, Sci-Fi",
        actors: "Harrison Ford, Rutger Hauer, Sean Young",
        rental_rate: 2,
        rental_duration: "6 days",
        damage_cost: 4
    },
    {
        title: "Blade Runner 2049",
        description: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
        release_date: "2017-10-06",
        img: "tt1856101.jpg",
        thumb: "thumb_tt1856101.png",
        running_time: "164 min",
        rating: "R",
        box_office: "$92,071,675",
        genre: "Action, Drama, Mystery",
        actors: "Harrison Ford, Ryan Gosling, Ana de Armas",
        rental_rate: 6,
        rental_duration: "7 days",
        damage_cost: 8
    },
    {
        title: "My Neighbor Totoro",
        description: "When two girls move to the country to be near their ailing mother, they have adventures with the wondrous forest spirits who live nearby.",
        release_date: "1990-07-13",
        img: "tt0096283.jpg",
        thumb: "thumb_tt0096283.png",
        running_time: "86 min",
        rating: "G",
        box_office: "$2,250,213",
        genre: "Animation, Comedy, Family",
        actors: "Hitoshi Takagi, Noriko Hidaka, Chika Sakamoto",
        rental_rate: 10,
        rental_duration: "3 days",
        damage_cost: 12
    },
    {
        title: "Klaus",
        description: "A simple act of kindness always sparks another, even in a frozen, faraway place. When Smeerensburg's new postman, Jesper, befriends toymaker Klaus, their gifts melt an age-old feud and deliver a sleigh full of holiday traditions.",
        release_date: "2019-11-15",
        img: "tt4729430.jpg",
        thumb: "thumb_tt4729430.png",
        running_time: "96 min",
        rating: "PG",
        box_office: "N/A",
        genre: "Animation, Adventure, Comedy",
        actors: "Jason Schwartzman, J.K. Simmons, Rashida Jones",
        rental_rate: 2,
        rental_duration: "6 days",
        damage_cost: 4
    },
    {
        title: "Ford v Ferrari",
        description: "American car designer Carroll Shelby and driver Ken Miles battle corporate interference and the laws of physics to build a revolutionary race car for Ford in order to defeat Ferrari at the 24 Hours of Le Mans in 1966.",
        release_date: "2019-11-15",
        img: "tt1950186.jpg",
        thumb: "thumb_tt1950186.png",
        running_time: "152 min",
        rating: "PG-13",
        box_office: "$117,624,357",
        genre: "Action, Biography, Drama",
        actors: "Matt Damon, Christian Bale, Jon Bernthal",
        rental_rate: 16,
        rental_duration: "7 days",
        damage_cost: 18
    },
    {
        title: "Howl's Moving Castle",
        description: "When an unconfident young woman is cursed with an old body by a spiteful witch, her only chance of breaking the spell lies with a self-indulgent yet insecure young wizard and his companions in his legged, walking castle.",
        release_date: "2005-06-17",
        img: "tt0347149.jpg",
        thumb: "thumb_tt0347149.png",
        running_time: "119 min",
        rating: "PG",
        box_office: "$5,576,743",
        genre: "Animation, Adventure, Family",
        actors: "Chieko Baishô, Takuya Kimura, Tatsuya Gashûin",
        rental_rate: 8,
        rental_duration: "4 days",
        damage_cost: 10
    }
]
